#define NUL       Chr(0)
#define NULNUL    Chr(0) & Chr(0)
#define CR        Chr(13)
#define LF        Chr(10)
#define CRLF      Chr(13) & Chr(10)
#define CRLFCRLF  Chr(13) & Chr(10) & Chr(13) & Chr(10)
#define CRCRLF    Chr(13) & Chr(13) & Chr(10)
#define A_TAB     Chr(9)
#define V_TAB     Chr(11)
#define BS        Chr(8)
#define FF        Chr(12)
#define BEL       Chr(7)
